---
# tasks file for webserver
- name: Start webserver
  community.docker.docker_container:
    name: "{{ webserver_image_name | default('webserver') }}"
    tag: "{{ webserver_version | default('latest') }}"
    image: "{{ [dockerhub_username, webserver_image_name] | join('/') | default('artempvl/webserver') }}"
    pull: yes
    detach: yes
    state: started
    published_ports:
      - "{{ webserver_port | default(8080) }}:8080"
    container_default_behavior: compatibility
