---
# tasks file for buildwebserver
- name: Download project source
  ansible.builtin.git:
    clone: yes
    force: yes
    dest: /source
    repo: {{ source_repository_url }}

- name: Build war file from source
  community.docker.docker_container:
    image: {{ build_server_name | default('build_server') }}
    name: {{ build_server_name | default('build_server') }}
    auto_remove: yes
    container_default_behavior: compatibility
    mounts:
      source: /source
      target: /source
      type: bind
    restart: yes
    state: started

- name: Copy created war file for webserver image
  ansible.builtin.copy:
    src: /source/target/*.war
    dest: /war/
    force: yes
    remote_src: yes

- name: Login into docker hub
  community.docker.docker_login:
    username: {{ dockerhub_username }}
    password: {{ dockerhub_token }}

- name: Create and upload webserver image
  community.docker.docker_image:
    build:
      path: .
      rm: yes
      pull: no
    repository: {{ repository_name | default('artempvl') }}
    name: {{ webserver_image_name | default('webserver') }}
    tag: {{ webserver_version | default('latest') }}
    source: build
    push: yes
    state: present

- name: Clean up unnecessary files
  ansible.builtin.file: path={{item}} state=absent
  with_items:
    - /war
    - /source
...